In [1]:
import pandas as pd
import numpy as np

In [2]:
#read in data
df = pd.read_csv('Life_Expectancy_Data.csv',sep=r'\s*,\s*', engine='python')

df.describe()


Year  Life expectancy  Adult Mortality  infant deaths  \
count  2938.000000      2928.000000      2928.000000    2938.000000   
mean   2007.518720        69.224932       164.796448      30.303948   
std       4.613841         9.523867       124.292079     117.926501   
min    2000.000000        36.300000         1.000000       0.000000   
25%    2004.000000        63.100000        74.000000       0.000000   
50%    2008.000000        72.100000       144.000000       3.000000   
75%    2012.000000        75.700000       228.000000      22.000000   
max    2015.000000        89.000000       723.000000    1800.000000   

           Alcohol  percentage expenditure  Hepatitis B        Measles  \
count  2744.000000             2938.000000  2385.000000    2938.000000   
mean      4.602861              738.251295    80.940461    2419.592240   
std       4.052413             1987.914858    25.070016   11467.272489   
min       0.010000                0.000000     1.000000       0.000000   
25%       0.877500                4.685343    77.000000       0.000000   
50%       3.755000               64.912906    92.000000      17.000000   
75%       7.702500              441.534144    97.000000     360.250000   
max      17.870000            19479.911610    99.000000  212183.000000   

               BMI  under-five deaths        Polio  Total expenditure  \
count  2904.000000        2938.000000  2919.000000         2712.00000   
mean     38.321247          42.035739    82.550188            5.93819   
std      20.044034         160.445548    23.428046            2.49832   
min       1.000000           0.000000     3.000000            0.37000   
25%      19.300000           0.000000    78.000000            4.26000   
50%      43.500000           4.000000    93.000000            5.75500   
75%      56.200000          28.000000    97.000000            7.49250   
max      87.300000        2500.000000    99.000000           17.60000   

        Diphtheria     HIV/AIDS            GDP    Population  \
count  2919.000000  2938.000000    2490.000000  2.286000e+03   
mean     82.324084     1.742103    7483.158469  1.275338e+07   
std      23.716912     5.077785   14270.169342  6.101210e+07   
min       2.000000     0.100000       1.681350  3.400000e+01   
25%      78.000000     0.100000     463.935626  1.957932e+05   
50%      93.000000     0.100000    1766.947595  1.386542e+06   
75%      97.000000     0.800000    5910.806335  7.420359e+06   
max      99.000000    50.600000  119172.741800  1.293859e+09   

       thinness  1-19 years  thinness 5-9 years  \
count           2904.000000         2904.000000   
mean               4.839704            4.870317   
std                4.420195            4.508882   
min                0.100000            0.100000   
25%                1.600000            1.500000   
50%                3.300000            3.300000   
75%                7.200000            7.200000   
max               27.700000           28.600000   

       Income composition of resources    Schooling  
count                      2771.000000  2775.000000  
mean                          0.627551    11.992793  
std                           0.210904     3.358920  
min                           0.000000     0.000000  
25%                           0.493000    10.100000  
50%                           0.677000    12.300000  
75%                           0.779000    14.300000  
max                           0.948000    20.700000

In [49]:
#remove categorical data
df = df._get_numeric_data()

#Deal with missing data
df = df[df['Life expectancy'].notna()] #drop rows without life expectancy value
df= df.fillna(df.mean())# impute other columns with the columns mean



#create numpy matrices
X = df.drop('Life expectancy',axis=1).to_numpy()
X=np.append(np.ones((X.shape[0],1)),X,axis=1) #add column of 1s
y = df['Life expectancy'].to_numpy()


#initialising weights
theta = np.zeros(X.shape[1])
n=df.shape[0]

#parameters
epsilon = 0.1
learning_rate = 0.1

In [50]:
df.describe()

Year  Life expectancy  Adult Mortality  infant deaths  \
count  2928.00000      2928.000000      2928.000000    2928.000000   
mean   2007.50000        69.224932       164.796448      30.407445   
std       4.61056         9.523867       124.292079     118.114450   
min    2000.00000        36.300000         1.000000       0.000000   
25%    2003.75000        63.100000        74.000000       0.000000   
50%    2007.50000        72.100000       144.000000       3.000000   
75%    2011.25000        75.700000       228.000000      22.000000   
max    2015.00000        89.000000       723.000000    1800.000000   

           Alcohol  percentage expenditure  Hepatitis B        Measles  \
count  2928.000000             2928.000000  2928.000000    2928.000000   
mean      4.614856              740.321185    80.960842    2427.855874   
std       3.914923             1990.930605    22.531361   11485.970937   
min       0.010000                0.000000     1.000000       0.000000   
25%       1.107500                4.853964    80.960842       0.000000   
50%       4.160000               65.611455    87.000000      17.000000   
75%       7.400000              442.614322    96.000000     362.250000   
max      17.870000            19479.911610    99.000000  212183.000000   

               BMI  under-five deaths        Polio  Total expenditure  \
count  2928.000000        2928.000000  2928.000000        2928.000000   
mean     38.235394          42.179303    82.548298           5.930163   
std      19.850184         160.700547    23.340548           2.385478   
min       1.000000           0.000000     3.000000           0.370000   
25%      19.400000           0.000000    78.000000           4.370000   
50%      43.000000           4.000000    93.000000           5.930163   
75%      56.100000          28.000000    97.000000           7.330000   
max      77.600000        2500.000000    99.000000          17.600000   

        Diphtheria     HIV/AIDS            GDP    Population  \
count  2928.000000  2928.000000    2928.000000  2.928000e+03   
mean     82.321416     1.747712    7494.210719  1.276454e+07   
std      23.629576     5.085542   13157.128331  5.390628e+07   
min       2.000000     0.100000       1.681350  3.400000e+01   
25%      78.000000     0.100000     578.797095  4.181205e+05   
50%      93.000000     0.100000    3112.560501  3.640009e+06   
75%      97.000000     0.800000    7494.210719  1.276454e+07   
max      99.000000    50.600000  119172.741800  1.293859e+09   

       thinness  1-19 years  thinness 5-9 years  \
count           2928.000000         2928.000000   
mean               4.850622            4.881423   
std                4.396597            4.484890   
min                0.100000            0.100000   
25%                1.600000            1.600000   
50%                3.400000            3.400000   
75%                7.100000            7.200000   
max               27.700000           28.600000   

       Income composition of resources    Schooling  
count                      2928.000000  2928.000000  
mean                          0.627419    11.999639  
std                           0.205131     3.253691  
min                           0.000000     0.000000  
25%                           0.504000    10.300000  
50%                           0.662000    12.100000  
75%                           0.773000    14.100000  
max                           0.948000    20.700000

In [51]:
print(X)
print(y)

[[1.000e+00 2.015e+03 2.630e+02 ... 1.730e+01 4.790e-01 1.010e+01]
 [1.000e+00 2.014e+03 2.710e+02 ... 1.750e+01 4.760e-01 1.000e+01]
 [1.000e+00 2.013e+03 2.680e+02 ... 1.770e+01 4.700e-01 9.900e+00]
 ...
 [1.000e+00 2.002e+03 7.300e+01 ... 1.300e+00 4.270e-01 1.000e+01]
 [1.000e+00 2.001e+03 6.860e+02 ... 1.700e+00 4.270e-01 9.800e+00]
 [1.000e+00 2.000e+03 6.650e+02 ... 1.120e+01 4.340e-01 9.800e+00]]
[65.  59.9 59.9 ... 44.8 45.3 46. ]


In [52]:
def cost(X,y):
    h= np.dot(X,theta)
    print(h)
    return (1/(2*n))*np.sum(np.square(h-y))

In [53]:
print(cost(X,y))

[0. 0. 0. ... 0. 0. 0.]
2441.382120901639
